### ISSUE TITLE
Specify a default club in extension options.

### ISSUE THREAD

**Issue by ryantbd** [maihq/rubu-chrome-extension#3]
Yo, I just tried to save some pages and publish to the `frontend-talk` club. After I clicked the extension icon, it just says `saved <page title>`, but I couldn't the page in any clubs I've joined.

Can you provide an option to specify a default club? It might be helpful.

**Comment by bitinn** [comment]
Actually they are stored under your profile page, see a new tab named `个人收藏`, it's a private collection.

My goal is to add sharing options there: so you can basically collect pages during your daily browsing, but come back to cherrypick the ones you would like to share.

**Comment by ryantbd** [comment]
@bitinn Oops, just found this feature, it looks like a mini-sized [Pinboard](https://pinboard.in). Nice work!

**Comment by bitinn** [comment]
This is now possible by visiting your profile page > personal bookmarks > and click share button

**Comment by ryantbd** [comment]
@bitinn Awesome!
